# Generated by Django 5.2.4 on 2025-07-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memeber',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='memeber',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
